# Generated by Django 2.2.15 on 2020-11-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageurl',
            field=models.URLField(blank=True),
        ),
    ]
